services:
  postgres:
    container_name: calculator-postgres
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
      TZ: 'Europe/Moscow'
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    networks:
      - calc-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - calc-network

networks:
  calc-network:
    driver: bridge

volumes:
  dbdata:
