logger:
  level: "INFO"
  file: "./runtime/log.log"

storage:
  type: "psql" #memory,psql
  timeout: "3"
  debug: "true"

server:
  host: "localhost"
  port: "8080"

grpc_server:
  host: "localhost"
  port: "50051"