logger:
  level: "INFO"
  file: "./runtime/log.log"

storage:
  type: "psql" #memory,psql
  timeout: "3"
  debug: "true"

server:
  host: "localhost"
  port: "8080"

rabbit:
  host: "localhost"
  port: "5672"
  queue: "scheduler"

options:
  interval: "30s"
  days: "3"