// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: api/EventService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DateStart     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dateStart,proto3" json:"dateStart,omitempty"`
	DateEnd       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dateEnd,proto3" json:"dateEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetDateStart() *timestamppb.Timestamp {
	if x != nil {
		return x.DateStart
	}
	return nil
}

func (x *Event) GetDateEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.DateEnd
	}
	return nil
}

type BaseEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEventRequest) Reset() {
	*x = BaseEventRequest{}
	mi := &file_api_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEventRequest) ProtoMessage() {}

func (x *BaseEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEventRequest.ProtoReflect.Descriptor instead.
func (*BaseEventRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *BaseEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type BaseEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*BaseEventResponse_Id
	//	*BaseEventResponse_Error
	Response      isBaseEventResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEventResponse) Reset() {
	*x = BaseEventResponse{}
	mi := &file_api_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEventResponse) ProtoMessage() {}

func (x *BaseEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEventResponse.ProtoReflect.Descriptor instead.
func (*BaseEventResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *BaseEventResponse) GetResponse() isBaseEventResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *BaseEventResponse) GetId() string {
	if x != nil {
		if x, ok := x.Response.(*BaseEventResponse_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *BaseEventResponse) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*BaseEventResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isBaseEventResponse_Response interface {
	isBaseEventResponse_Response()
}

type BaseEventResponse_Id struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type BaseEventResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*BaseEventResponse_Id) isBaseEventResponse_Response() {}

func (*BaseEventResponse_Error) isBaseEventResponse_Response() {}

type DeleteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEvent) Reset() {
	*x = DeleteEvent{}
	mi := &file_api_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEvent) ProtoMessage() {}

func (x *DeleteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEvent.ProtoReflect.Descriptor instead.
func (*DeleteEvent) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteEvent   *DeleteEvent           `protobuf:"bytes,1,opt,name=deleteEvent,proto3" json:"deleteEvent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetDeleteEvent() *DeleteEvent {
	if x != nil {
		return x.DeleteEvent
	}
	return nil
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*DeleteResponse_Success
	//	*DeleteResponse_Error
	Response      isDeleteResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetResponse() isDeleteResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		if x, ok := x.Response.(*DeleteResponse_Success); ok {
			return x.Success
		}
	}
	return false
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		if x, ok := x.Response.(*DeleteResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isDeleteResponse_Response interface {
	isDeleteResponse_Response()
}

type DeleteResponse_Success struct {
	Success bool `protobuf:"varint,1,opt,name=success,proto3,oneof"`
}

type DeleteResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DeleteResponse_Success) isDeleteResponse_Response() {}

func (*DeleteResponse_Error) isDeleteResponse_Response() {}

type ListEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          int64                  `protobuf:"varint,1,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEvents) Reset() {
	*x = ListEvents{}
	mi := &file_api_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvents) ProtoMessage() {}

func (x *ListEvents) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvents.ProtoReflect.Descriptor instead.
func (*ListEvents) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *ListEvents) GetDays() int64 {
	if x != nil {
		return x.Days
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListEvent     *ListEvents            `protobuf:"bytes,1,opt,name=listEvent,proto3" json:"listEvent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetListEvent() *ListEvents {
	if x != nil {
		return x.ListEvent
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_EventService_proto protoreflect.FileDescriptor

const file_api_EventService_proto_rawDesc = "" +
	"\n" +
	"\x16api/EventService.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\tdateStart\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tdateStart\x124\n" +
	"\adateEnd\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\adateEnd\"6\n" +
	"\x10BaseEventRequest\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"I\n" +
	"\x11BaseEventResponse\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"\x1d\n" +
	"\vDeleteEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\rDeleteRequest\x124\n" +
	"\vdeleteEvent\x18\x01 \x01(\v2\x12.event.DeleteEventR\vdeleteEvent\"P\n" +
	"\x0eDeleteResponse\x12\x1a\n" +
	"\asuccess\x18\x01 \x01(\bH\x00R\asuccess\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\" \n" +
	"\n" +
	"ListEvents\x12\x12\n" +
	"\x04days\x18\x01 \x01(\x03R\x04days\">\n" +
	"\vListRequest\x12/\n" +
	"\tlistEvent\x18\x01 \x01(\v2\x11.event.ListEventsR\tlistEvent\"J\n" +
	"\fListResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xf2\x01\n" +
	"\x06Events\x12=\n" +
	"\x06Create\x12\x17.event.BaseEventRequest\x1a\x18.event.BaseEventResponse\"\x00\x12=\n" +
	"\x06Update\x12\x17.event.BaseEventRequest\x1a\x18.event.BaseEventResponse\"\x00\x127\n" +
	"\x06Delete\x12\x14.event.DeleteRequest\x1a\x15.event.DeleteResponse\"\x00\x121\n" +
	"\x04List\x12\x12.event.ListRequest\x1a\x13.event.ListResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_api_EventService_proto_rawDescOnce sync.Once
	file_api_EventService_proto_rawDescData []byte
)

func file_api_EventService_proto_rawDescGZIP() []byte {
	file_api_EventService_proto_rawDescOnce.Do(func() {
		file_api_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)))
	})
	return file_api_EventService_proto_rawDescData
}

var file_api_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_EventService_proto_goTypes = []any{
	(*Event)(nil),                 // 0: event.Event
	(*BaseEventRequest)(nil),      // 1: event.BaseEventRequest
	(*BaseEventResponse)(nil),     // 2: event.BaseEventResponse
	(*DeleteEvent)(nil),           // 3: event.DeleteEvent
	(*DeleteRequest)(nil),         // 4: event.DeleteRequest
	(*DeleteResponse)(nil),        // 5: event.DeleteResponse
	(*ListEvents)(nil),            // 6: event.ListEvents
	(*ListRequest)(nil),           // 7: event.ListRequest
	(*ListResponse)(nil),          // 8: event.ListResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_EventService_proto_depIdxs = []int32{
	9,  // 0: event.Event.dateStart:type_name -> google.protobuf.Timestamp
	9,  // 1: event.Event.dateEnd:type_name -> google.protobuf.Timestamp
	0,  // 2: event.BaseEventRequest.event:type_name -> event.Event
	3,  // 3: event.DeleteRequest.deleteEvent:type_name -> event.DeleteEvent
	6,  // 4: event.ListRequest.listEvent:type_name -> event.ListEvents
	0,  // 5: event.ListResponse.events:type_name -> event.Event
	1,  // 6: event.Events.Create:input_type -> event.BaseEventRequest
	1,  // 7: event.Events.Update:input_type -> event.BaseEventRequest
	4,  // 8: event.Events.Delete:input_type -> event.DeleteRequest
	7,  // 9: event.Events.List:input_type -> event.ListRequest
	2,  // 10: event.Events.Create:output_type -> event.BaseEventResponse
	2,  // 11: event.Events.Update:output_type -> event.BaseEventResponse
	5,  // 12: event.Events.Delete:output_type -> event.DeleteResponse
	8,  // 13: event.Events.List:output_type -> event.ListResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_EventService_proto_init() }
func file_api_EventService_proto_init() {
	if File_api_EventService_proto != nil {
		return
	}
	file_api_EventService_proto_msgTypes[2].OneofWrappers = []any{
		(*BaseEventResponse_Id)(nil),
		(*BaseEventResponse_Error)(nil),
	}
	file_api_EventService_proto_msgTypes[5].OneofWrappers = []any{
		(*DeleteResponse_Success)(nil),
		(*DeleteResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_EventService_proto_rawDesc), len(file_api_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_EventService_proto_goTypes,
		DependencyIndexes: file_api_EventService_proto_depIdxs,
		MessageInfos:      file_api_EventService_proto_msgTypes,
	}.Build()
	File_api_EventService_proto = out.File
	file_api_EventService_proto_goTypes = nil
	file_api_EventService_proto_depIdxs = nil
}
